name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: ${{ !(github.ref == 'refs/heads/main') }} # if main, then false
          
      - run: echo "hello"
