name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      path:
        description: 'path to checkout'     
        required: true
        default: ''

env:
  ACTIONS_RUNNER_DEBUG: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: ${{ !(github.ref == 'refs/heads/main') }} # if main, then false
          path: ${{ github.event.inputs.path == '' && github.workspace || github.event.inputs.path }} # if path = '', clone to github.workspace, otherwise clone to that path
          
      - run: echo "hello" > file.txt
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: format('Artifact-{0}-{1}', 'Build', github.ref_name }})
          path: file.txt
  
