name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      path:
        description: 'path to checkout'     
        required: true
        default: ''

env:
  ACTIONS_RUNNER_DEBUG: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: ${{ !(github.ref == 'refs/heads/main') }} # if main, then false
          path: ${{ github.event.inputs.path == '' && github.workspace || github.event.inputs.path }} # if path = '', clone to github.workspace, otherwise clone to that path
          
      - run: echo "hello" > file.txt
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: ${{ format('Artifact-{0}-{1}{2}', 'Build', github.ref_name, (github.ref != 'refs/heads/main') && '-beta' || '' ) }} # name the artifact we're publishing - append "-beta" if not main branch
          path: file.txt
  
      # - name: force a failure
      #   run: abcdefg
        
      - name: next step
        run: echo "hello"
        # if: success() # this is implied
        
      - name: next step1
        run: echo "hello"
        # if: success() # this is implied
        
      - name: next step2
        run: echo "hello"
        # if: success() # this is implied
        
      - name: always run
        run: echo "always running!"
        if: always()
        
      - name: only run if failure
        run: echo "only run if failure"
        if: failure()
        
      - name: only run if success
        run: echo "only run if success"
        if: success()
        
      - name: super important step
        run: | 
          echo "only run if success"
          # if successful, then make your own output or environment variable
          echo "important_step_result=true" >> $GITHUB_ENV
        if: always()
        
      - name: only run IF important step was successful
        run: echo "only run if success"
        if: ${{ success() && env.important_step_result == 'true' }}
        
