name: master and main

on: 
  push:
  workflow_dispatch:
    

jobs:
  master-main:
    runs-on: ubuntu-latest
    if:  ${{ (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/master') }} # if main or master, then run
    steps:
    - run: echo "hello"

